%YAML 1.2
---
profile: default
variables: {}
engine:
    type: spark
    master: local[*]
    submit: 
        detect: true
        jars: []
        packages: []
        py-files: []
        conf: {}

providers: {}
resources: {}

loggers:
    root:
        severity: info
    datalabframework:
        name: dlf
        stream:
            enable: false
            severity: notice
        stdout:
            enable: true
            severity: notice
        file:
            enable: false
            severity: info
        kafka:
            enable: false
            severity: info
            hosts: []
            topic: dlf

---
profile: prod
---
profile: stage
---
profile: test
---
profile: dev
